# Numpy 연습하기

데이터 분석을 위한 기본적인 Numpy 사용 방법입니다.

## 1. Numpy 사용하기
소스코드 최상단에 아래와 같이 입력합니다. 보통 np를 약자로 사용한다.

In [1]:
import numpy as np

In [2]:
arr = np.array(list)
type(arr)

numpy.ndarray

## 2. Numpy 배열 만들기
Numpy 배열은 데이터 분석에서 가장 많이 사용되는 배열 중 하나이다.<br>
크게 벡터(vector)와 매트릭스(matrix)로 나눌 수 있다.<br>

 - 벡터: 1차원 배열
 - 매트릭스: 2차원 배열(1차원만 사용 가능)

In [3]:
# [1,2,3,4,5]

# [ [1,2,3,4], [2,3,4,5], [5,6,7,8]]


배열을 생성하는 방법은 여러가지가 있다.

    1. 파이썬 리스트 이용: np.array([list])
    2. 0또는 1로 채우기: np.zeros(), np.ones()
    3. 일정한 간격을 가지는 숫자 배열: np.arange()
    4. 일정 범위 안에서 일정 갯수를 가진 배열: np.linspace()
    5. 랜덤 값을 가지는 배열: np.random.rand() / randint() / randn()

### np.array()

In [4]:
# 1차원 배열 = 벡터
list_array = [1,2,3,4,5]
list_array

[1, 2, 3, 4, 5]

In [5]:
type(list_array)

list

In [6]:
# arr = numpy.array(list_array)
arr = np.array(list_array)
arr

array([1, 2, 3, 4, 5])

In [7]:
type(arr)

numpy.ndarray

In [8]:
# 2차원 배열 = 매트릭스
mat = [[1,2],[3,4]]
mat

[[1, 2], [3, 4]]

In [9]:
m_arr = np.array(mat)
m_arr

array([[1, 2],
       [3, 4]])

# 1. ndarray 생성 후 변수에 저장하기
[0, 1, 2]와 [3, 4, 5]를 행으로 갖는 2차원 ndarray를 만들고, new_arr 변수에 저장합니다.

In [10]:
new_arr = np.array([[0,1,2],[3,4,5]])
new_arr

array([[0, 1, 2],
       [3, 4, 5]])

In [11]:
type(new_arr)

numpy.ndarray

### np.zeros() / np.ones()

In [12]:
# 모든 요소가 0 값을 가지는 배열 생성
np.zeros(4)

array([0., 0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
# 모든 요소가 1 값을 가지는 배열 생성
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# 2. 0으로 채워진 ndarray 만들기
숫자 0으로 채워진 3x4 ndarray를 만들어 봅니다. 

In [16]:
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### np.arange()

In [17]:
list(range(10)) # 0부터 시작 10까지 숫자를 가져와라 0 <= x < 10

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [18]:
# 0부터 10까지, 간격 1을 가지는 배열
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
# 0부터 10까지, 간격 2를 가지는 배열
np.arange(0, 11, 2) # -> 0 <= x < 11 / 2

array([ 0,  2,  4,  6,  8, 10])

# 3. 일정 간격을 가진 ndarray 만들기
5부터 15까지, 간격 3을 가지는 ndarray를 만들어 봅니다. 

In [20]:
arr = np.arange(5,16,3)
arr

array([ 5,  8, 11, 14])

### np.random.rand() / np.random.randn() / np.random.randint()

In [21]:
# 0과 1범위 내의 연속 균등 분포(uniform)에서 랜덤으로 값을 가져와 생성
np.random.rand(5)

array([0.27128366, 0.84008286, 0.32094654, 0.05086321, 0.2397808 ])

In [22]:
np.random.rand(5,5)

array([[0.29878901, 0.28861047, 0.90585779, 0.24927189, 0.40895694],
       [0.30611574, 0.42446993, 0.93977598, 0.51276637, 0.39711449],
       [0.04473361, 0.35899282, 0.52661722, 0.28806018, 0.76493041],
       [0.96399867, 0.73441356, 0.30307887, 0.45543388, 0.29750773],
       [0.59493246, 0.1040063 , 0.43624815, 0.75529439, 0.80094129]])

In [23]:
# 표준 정규 분포(standard normal)에서 랜덤으로 값을 가져와 생성
np.random.randn(5,5)

array([[ 0.35839804, -0.36669103, -0.77564334,  0.98527625, -1.17270957],
       [ 0.32394192, -0.50651691, -0.06082561, -0.74995151, -0.39897462],
       [-0.56617402, -2.01897558,  0.87224411,  0.3928138 , -0.27616642],
       [ 1.84354785, -1.43174796, -0.0441139 , -0.28772792,  2.04325017],
       [-0.89524655,  0.00724973, -0.87110979, -1.69407341,  0.628893  ]])

In [24]:
# 특정 범위 내에서 랜덤 정수형 숫자(int)를 가져와 생성
np.random.randint(1,1000)

18

In [25]:
np.random.randint(1,1000, 5)

array([ 23, 376, 409,  22, 171])

# 4. 배열의 연산

    1. 파이썬 리스트 연산과 비교
    2. 브로드캐스팅
    3. 연산속도 

In [26]:
temp_list = list(range(10))
temp_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [27]:
# 설명을 위해 의도적으로 발생시킨 오류
temp_list + 7

TypeError: can only concatenate list (not "int") to list

In [28]:
np.arange(0, 11) + 7

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [29]:
m_arr 

array([[1, 2],
       [3, 4]])

In [30]:
m_arr + m_arr

array([[2, 4],
       [6, 8]])

In [31]:
m_arr + [10, 20]

array([[11, 22],
       [13, 24]])

In [32]:
m_arr + 10

array([[11, 12],
       [13, 14]])

### 연산 속도

In [33]:
big_data = np.arange(10000000)
len(big_data)

10000000

In [34]:
%%time
add_result = []
for num in big_data:
    add_result.append(num+10)
print(np.array(add_result))

[      10       11       12 ... 10000007 10000008 10000009]
CPU times: user 1.41 s, sys: 95.3 ms, total: 1.5 s
Wall time: 1.52 s


In [35]:
%%time
big_data+10

CPU times: user 5.78 ms, sys: 5.73 ms, total: 11.5 ms
Wall time: 9.43 ms


array([      10,       11,       12, ..., 10000007, 10000008, 10000009])

# 5. 여러가지 배열 연산
여러 가지 배열 연산에 대해서 실습합니다.

In [36]:
test_arr = np.arange(12).reshape(3, 4)
test_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
# test_arr의 모든 원소에 숫자 3을 더한다.
test_arr + 3

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [38]:
# test_arr의 모든 원소에 숫자 3을 더한다.
test_arr - 3

array([[-3, -2, -1,  0],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [39]:
# test_arr의 모든 원소에 숫자 3을 곱한다.
test_arr * 3

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

In [40]:
# test_arr의 모든 원소에 숫자 3으로 나눈다.
test_arr / 3

array([[0.        , 0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        , 2.33333333],
       [2.66666667, 3.        , 3.33333333, 3.66666667]])

# 6. 배열 요소 접근 및 범위 선택

    1. 배열 요소 접근 방식은 파이썬 리스트와 동일합니다.
    2. 범위 접근자(:) 사용 시 범위에 주의합시다 ( 1:5 는 1부터 4까지를 의미 )
    3. 배열 복사(메모리 문제 방지): XXX.copy()
    4. 특정 조건에 해당하는 데이터 선택은 인덱스를 사용합니다

In [41]:
arr = np.array([[1,3,5], [7,9,11], [2,4,6], [8,10,12]])
arr

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [ 2,  4,  6],
       [ 8, 10, 12]])

In [42]:
arr[0]

array([1, 3, 5])

In [43]:
arr[1:3]

array([[ 7,  9, 11],
       [ 2,  4,  6]])

In [44]:
arr[0, 1]

3

In [45]:
arr[:, 1:]

array([[ 3,  5],
       [ 9, 11],
       [ 4,  6],
       [10, 12]])

In [46]:
arr2 = arr.copy()

In [47]:
arr2[0, 0] = 10
arr2

array([[10,  3,  5],
       [ 7,  9, 11],
       [ 2,  4,  6],
       [ 8, 10, 12]])

# 7. ndarray 변수에서 데이터 추출하기
test_arr 배열에 대하여 문제를 풀어봅니다.

In [48]:
test_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
# 인덱스 1에 해당하는 데이터를 추출합니다. 
test_arr[1]

array([4, 5, 6, 7])

In [50]:
# 인덱스 1부터 2까지 해당하는 데이터를 추출합니다. 
test_arr[1:3]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
# 인덱스 (2, 3)에 해당하는 데이터를 추출합니다. 
test_arr[2, 3]

11

# 8. 배열 다루기
데이터 분석 수행 시 배열을 쪼개고, 합쳐야 할 때를 빈번하게 마주친다.<br>
또한, 배열의 자료형이 맞지 않아 특정 기능을 실행할 수 없는 경우도 발생한다.<br>
이러한 작업을 하려면 우선 numpy 자료형의 모양을 확인하고, <br>
필요하다면 원하는 모양으로 변환하는 과정이 필요하다. 

### 배열의 모양 확인하고 변경하기

    1. 배열 모양 확인: XXX.shape() 
    2. 배열 내의 데이터 자료형 확인: XXX.dtype
    3. 배열 모양 변경: XXX.reshape()
    4. 데이터 타입 변경: XXX.astype()
    
※ 배열 모양은 (row x col) 형태로 표현됩니다

In [52]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
arr.shape

(2, 3)

In [54]:
arr.ndim

2

In [55]:
arr.size

6

In [56]:
arr.dtype

dtype('int64')

In [57]:
arr = np.array([[1,2,3],[4,5,6]], dtype='float32')
arr

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [58]:
arr.dtype

dtype('float32')

In [59]:
arr2 = np.array(['1','2','3'])
arr2

array(['1', '2', '3'], dtype='<U1')

In [60]:
arr2.dtype

dtype('<U1')

# 9. ndim, shape, size, dtype 확인하기 
m_arr 배열의 ndim, shape, size, dtype을 확인하고 그 결과를 살펴봅니다.

In [61]:
m_arr

array([[1, 2],
       [3, 4]])

In [62]:
m_arr.ndim

2

In [63]:
m_arr.shape

(2, 2)

In [64]:
m_arr.size

4

In [65]:
m_arr.dtype

dtype('int64')

### np.reshape()

In [66]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [67]:
arr.reshape(3,2)

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float32)

In [68]:
arr.reshape(6,1)

array([[1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.]], dtype=float32)

In [69]:
arr.reshape(1, 6)

array([[1., 2., 3., 4., 5., 6.]], dtype=float32)

In [70]:
arr.reshape(-1)

array([1., 2., 3., 4., 5., 6.], dtype=float32)

In [71]:
arr.reshape(-1, 3)

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

# 10. 배열 변환하기
다음 배열을 (28, 28, 3) 형태로 변경합니다.

In [72]:
arr = np.random.randint(0, 10, size=2352)
arr.shape

(2352,)

In [73]:
arr.reshape(28,28,3).shape

(28, 28, 3)

### 배열 쪼개고 / 합치기
일반적으로, 데이터 분석에서 다루는 모든 자료는 2차원 배열이다.<br>
배열의 열 또는 행을 기준으로 데이터를 쪼개고 합치는 방법이 기본이며,<br>
가끔 특정 '조건'에 해당하는 열 또는 행에 대해 연산을 할 줄도 알아야 한다.

In [74]:
# arr1 = 5x5 array
# arr2 = 3x1 array
# arr3 = 3x1 array

arr1 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
arr2 = np.zeros(3)
arr3 = np.ones(2)

print(arr1)
print(arr2)
print(arr3)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[0. 0. 0.]
[1. 1.]


### np.concatenate()

In [75]:
arr2

array([0., 0., 0.])

In [76]:
arr3

array([1., 1.])

In [77]:
# 1차원 배열 합치기
con = np.concatenate((arr2, arr3), axis=0)
print(con.shape)
con

(5,)


array([0., 0., 0., 1., 1.])

In [78]:
arr1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [79]:
# row 기준으로 합치기
con2 = np.concatenate((arr1, arr1), axis=0)
print(con2.shape)
con2

(10, 2)


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [80]:
# col 기준으로 합치기
con3 = np.concatenate((arr1, arr1), axis=1)
print(con3.shape)
con3

(5, 4)


array([[ 1,  2,  1,  2],
       [ 3,  4,  3,  4],
       [ 5,  6,  5,  6],
       [ 7,  8,  7,  8],
       [ 9, 10,  9, 10]])

In [81]:
# # col을 기준으로 합치려면 reshape이 필요
# print(arr1.shape)
# print(con.shape)
# con = con.reshape(5,1)
# con

In [82]:
# # col 기준으로 합치기
# rst = np.concatenate((arr1, con), axis=1)
# rst

### 마스킹 연산 - 조건에 맞는 데이터 처리

In [83]:
rst = con3.copy()
rst

array([[ 1,  2,  1,  2],
       [ 3,  4,  3,  4],
       [ 5,  6,  5,  6],
       [ 7,  8,  7,  8],
       [ 9, 10,  9, 10]])

In [84]:
rst > 5

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [85]:
rst[rst > 5]

array([ 6,  6,  7,  8,  7,  8,  9, 10,  9, 10])

In [86]:
rst[:, 2] < 5

array([ True,  True, False, False, False])

In [87]:
rst[rst[:, 2] < 5]

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [88]:
rst[1] == 3

array([ True, False,  True, False])

In [89]:
rst[:, rst[1]==3]

array([[1, 1],
       [3, 3],
       [5, 5],
       [7, 7],
       [9, 9]])

# 11. rst에서 값 추출하기
rst에서 짝수에 해당하는 값을 추출합니다. (힌트: 나머지를 구하는 파이썬 % 연산자 활용)

In [90]:
rst

array([[ 1,  2,  1,  2],
       [ 3,  4,  3,  4],
       [ 5,  6,  5,  6],
       [ 7,  8,  7,  8],
       [ 9, 10,  9, 10]])

In [91]:
rst[rst[:,:]%2 == 0]

array([ 2,  2,  4,  4,  6,  6,  8,  8, 10, 10])

In [92]:
rst[:,:]%2 == 0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [93]:
rst[rst%2 == 0]

array([ 2,  2,  4,  4,  6,  6,  8,  8, 10, 10])